### PR TITLE
Refactor the functionality of generating reach points from a Venn diagram

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Review by jiayu-google — APPROVED** [review]
Great job! Thanks for further improving the readability of the elegant codes.

**Review by matthewclegg — APPROVED** [review]

**Comment by RonPinelliMRC** [comment]
Requested addition to Summary of Pending Pull Requests for Planning Evaluation Framework

**Comment by riemanli** [comment]
Hi @RonPinelliMRC. The PR is added to Summary of Pending Pull Requests for Planning Evaluation Framework. Thank you so much.

**Review by RonPinelliMRC — APPROVED** [review]
MRC approving based on cursory review after confirming non-independent code review on an exception basis. Experimental code will require independent review prior to publication of or reliance on results generated.

**Pull request merged**
