### PR TITLE
Colab for visualizing single publisher models

### PR DESCRIPTION
**Pull request by matthewclegg**

### CODE REVIEW

**Review by jiayu-google — APPROVED** [review]
Nice Colab.  I haven't seen any issues so far.  LMK if you need a careful review and I can comment directly on the Colab.

**Comment by RonPinelliMRC** [comment]
Should @jiayu-google perform careful review offered, before s/o?

**Comment by matthewclegg** [comment]
> Nice Colab. I haven't seen any issues so far. LMK if you need a careful review and I can comment directly on the Colab.

Thanks, Jiayu.  Would you mind doing a more thorough review?  (See Ron's comment below.)

**Review by jiayu-google — CHANGES_REQUESTED** [review]
@matthewclegg @RonPinelliMRC 
Here's a summary of my comments.  (I shared the details with Matthew offline.)
- Add labels to a couple of plots to call out, for example, under which spend fraction the curve is obtained.
- A minor comment on setting the y-labels of subplots in matplotlib.
- Extend the green curve in the last plot using a horizontal line.
- Question about the robustness to DP.

I will review again once Matthew make changes.

**Comment by matthewclegg** [comment]
I have updated the colab in response to Jiayu's comments.  The question of robustness to DP will be addressed in a future colab.

**Review by jiayu-google — APPROVED** [review]
LGTM, thank you Matt!

**Review by RonPinelliMRC — APPROVED** [review]
MRC approving based on cursory review after confirming non-independent code review on an exception basis. Experimental code will require independent review prior to publication of or reliance on results generated.

**Pull request merged**
