### PR TITLE
Move the changes in PR105 from Jiayu's branch to main.

### PR DESCRIPTION
**Pull request by jiayu-google**
[PR 105](https://github.com/world-federation-of-advertisers/planning-evaluation-framework/pull/105
) has already been approved, but I forgot to move the changes into main.   So, I'm creating this PR to update main.

### CODE REVIEW

**Comment by riemanli** [comment]
Hi @jiayu-google, any reason of not just merging PR105 into the main?

**Comment by jiayu-google** [comment]
Good question, Rieman...  I'm ashamed to say that I don't know how to edit PR 105 to merge into main...
(Now I'm merging commits into jiayu_univariate_mixed_poisson_optimizer from jiayu_class_dirac_mixture_single_publisher_model.  What is a way to modify the former branch to main?)

**Comment by riemanli** [comment]
Just for future reference, for an open PR, you can click the `Edit` button right to the PR title to change the base branch. But since #105 is already merged to this PR, as far as I know there is no way to reopen it and make changes. As a result, let's merge the changes in #105 through this PR.

**Review by riemanli — APPROVED** [review]
Exactly the same changes in #105 which was already approved.

**Pull request merged**
